# Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK]							
	set_property IOSTANDARD LVCMOS33 [get_ports CLK]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {Notes[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[11]}]
set_property PACKAGE_PIN V16 [get_ports {Notes[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[10]}]
set_property PACKAGE_PIN W16 [get_ports {Notes[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[9]}]
set_property PACKAGE_PIN W17 [get_ports {Notes[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[8]}]
set_property PACKAGE_PIN W15 [get_ports {Notes[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[7]}]
set_property PACKAGE_PIN V15 [get_ports {Notes[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[6]}]
set_property PACKAGE_PIN W14 [get_ports {Notes[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[5]}]
set_property PACKAGE_PIN W13 [get_ports {Notes[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[4]}]
set_property PACKAGE_PIN V2 [get_ports {Notes[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[3]}]
set_property PACKAGE_PIN T3 [get_ports {Notes[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[2]}]
set_property PACKAGE_PIN T2 [get_ports {Notes[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[1]}]
set_property PACKAGE_PIN R3 [get_ports {Notes[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Notes[0]}]
set_property PACKAGE_PIN W2 [get_ports {Octaves[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Octaves[0]}]
set_property PACKAGE_PIN U1 [get_ports {Octaves[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Octaves[1]}]
set_property PACKAGE_PIN T1 [get_ports {Octaves[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Octaves[2]}]
#set_property PACKAGE_PIN R2 [get_ports {sw[15]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]

#7 segment display
set_property PACKAGE_PIN W7 [get_ports {seven_segment_display[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[0]}]
set_property PACKAGE_PIN W6 [get_ports {seven_segment_display[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[1]}]
set_property PACKAGE_PIN U8 [get_ports {seven_segment_display[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[2]}]
set_property PACKAGE_PIN V8 [get_ports {seven_segment_display[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[3]}]
set_property PACKAGE_PIN U5 [get_ports {seven_segment_display[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[4]}]
set_property PACKAGE_PIN V5 [get_ports {seven_segment_display[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[5]}]
set_property PACKAGE_PIN U7 [get_ports {seven_segment_display[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[6]}]

#set_property PACKAGE_PIN V7 [get_ports dp]							
#	set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {seven_segment_display[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[7]}]
set_property PACKAGE_PIN U4 [get_ports {seven_segment_display[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[8]}]
set_property PACKAGE_PIN V4 [get_ports {seven_segment_display[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[9]}]
set_property PACKAGE_PIN W4 [get_ports {seven_segment_display[10]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment_display[10]}]


###Buttons
set_property PACKAGE_PIN U18 [get_ports Modes[0]]						
	set_property IOSTANDARD LVCMOS33 [get_ports Modes[0]]
set_property PACKAGE_PIN T18 [get_ports Modes[1]]						
	set_property IOSTANDARD LVCMOS33 [get_ports Modes[1]]
set_property PACKAGE_PIN W19 [get_ports Modes[2]]						
	set_property IOSTANDARD LVCMOS33 [get_ports Modes[2]]
set_property PACKAGE_PIN T17 [get_ports Modes[3]]						
	set_property IOSTANDARD LVCMOS33 [get_ports Modes[3]]
set_property PACKAGE_PIN U17 [get_ports Modes[4]]						
	set_property IOSTANDARD LVCMOS33 [get_ports Modes[4]]
 
##PWM Output
set_property PACKAGE_PIN N1 [get_ports {output}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {output}]

##VGA Connector
set_property PACKAGE_PIN G19 [get_ports {red[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property PACKAGE_PIN H19 [get_ports {red[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property PACKAGE_PIN J19 [get_ports {red[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property PACKAGE_PIN N19 [get_ports {red[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property PACKAGE_PIN N18 [get_ports {blue[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property PACKAGE_PIN J17 [get_ports {green[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property PACKAGE_PIN H17 [get_ports {green[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property PACKAGE_PIN G17 [get_ports {green[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property PACKAGE_PIN D17 [get_ports {green[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property PACKAGE_PIN P19 [get_ports hsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports vsync]